from core.models import Language, Material, Medium

english = Language.objects.create(name="English", frequency=141264)
german = Language.objects.create(name="German", frequency=20058)
french = Language.objects.create(name="French", frequency=19617)
spanish = Language.objects.create(name="Spanish", frequency=17669)
japanese = Language.objects.create(name="Japanese", frequency=13530)
Language.objects.create(name="Russian", frequency=11837)
Language.objects.create(name="Italian", frequency=8672)
chinese = Language.objects.create(name="Chinese", frequency=8439)
Language.objects.create(name="Portuguese", frequency=5765)
farsi = Language.objects.create(name="Persian", frequency=4727)
Language.objects.create(name="Polish", frequency=4551)
arabic = Language.objects.create(name="Arabic", frequency=4535)
Language.objects.create(name="Dutch", frequency=4436)
Language.objects.create(name="Ukrainian", frequency=3228)
hebrew = Language.objects.create(name="Hebrew", frequency=3059)
Language.objects.create(name="Swedish", frequency=2918)
Language.objects.create(name="Indonesian", frequency=2700)
Language.objects.create(name="Czech", frequency=2401)
korean = Language.objects.create(name="Korean", frequency=2013)
Language.objects.create(name="Finnish", frequency=1956)
Language.objects.create(name="Hungarian", frequency=1858)
vietnamese = Language.objects.create(name="Vietnamese", frequency=1798)
Language.objects.create(name="Catalan", frequency=1773)
Language.objects.create(name="Norwegian (Bokmål)", frequency=1608)
thai = Language.objects.create(name="Thai", frequency=1453)
hindi = Language.objects.create(name="Hindi", frequency=1406)
Language.objects.create(name="Danish", frequency=1151)
Language.objects.create(name="Romanian", frequency=1128)
greek = Language.objects.create(name="Greek", frequency=1102)
koine_greek = Language.objects.create(name="Koine Greek", frequency=0)
Language.objects.create(name="Serbian", frequency=1082)
Language.objects.create(name="Bengali", frequency=996)
Language.objects.create(name="Simple English", frequency=855)
Language.objects.create(name="Turkish", frequency=803)
Language.objects.create(name="Bulgarian", frequency=793)
Language.objects.create(name="Armenian", frequency=785)
Language.objects.create(name="Azerbaijani", frequency=668)
Language.objects.create(name="Basque", frequency=660)
Language.objects.create(name="Estonian", frequency=648)
Language.objects.create(name="Croatian", frequency=554)
Language.objects.create(name="Slovak", frequency=552)
Language.objects.create(name="Malay", frequency=519)
Language.objects.create(name="Galician", frequency=462)
Language.objects.create(name="Slovenian", frequency=426)
Language.objects.create(name="Tamil", frequency=401)
Language.objects.create(name="Esperanto", frequency=390)
Language.objects.create(name="Malayalam", frequency=361)
Language.objects.create(name="Lithuanian", frequency=359)
Language.objects.create(name="Marathi", frequency=355)
Language.objects.create(name="Georgian", frequency=327)
Language.objects.create(name="Albanian", frequency=301)
Language.objects.create(name="Kannada", frequency=300)
Language.objects.create(name="Latvian", frequency=297)
Language.objects.create(name="Urdu", frequency=274)
Language.objects.create(name="Belarusian", frequency=268)
Language.objects.create(name="Macedonian", frequency=260)
Language.objects.create(name="Cantonese", frequency=254)
Language.objects.create(name="Kazakh", frequency=233)
Language.objects.create(name="Serbo-Croatian", frequency=203)
Language.objects.create(name="Icelandic", frequency=191)
Language.objects.create(name="Bosnian", frequency=187)
Language.objects.create(name="Cebuano", frequency=172)
Language.objects.create(name="Telugu", frequency=170)
Language.objects.create(name="Afrikaans", frequency=166)
Language.objects.create(name="Norwegian (Nynorsk)", frequency=162)
latin = Language.objects.create(name="Latin", frequency=158)
Language.objects.create(name="Asturian", frequency=158)
welsh = Language.objects.create(name="Welsh", frequency=154)
Language.objects.create(name="Tagalog", frequency=145)
Language.objects.create(name="Javanese", frequency=136)
Language.objects.create(name="Konkani", frequency=136)
sanskrit = Language.objects.create(name="Sanskrit", frequency=134)
Language.objects.create(name="Uzbek", frequency=129)
swahili = Language.objects.create(name="Swahili", frequency=129)
Language.objects.create(name="Belarusian (Taraškievica)", frequency=122)
Language.objects.create(name="Breton", frequency=115)
Language.objects.create(name="Mongolian", frequency=115)
Language.objects.create(name="Burmese", frequency=114)
Language.objects.create(name="Egyptian Arabic", frequency=110)
egyptian = Language.objects.create(name="Ancient Egyptian", frequency=0)
irish = Language.objects.create(name="Irish", frequency=108)
Language.objects.create(name="Eastern Punjabi", frequency=108)
Language.objects.create(name="Scots", frequency=106)
Language.objects.create(name="Kurdish (Sorani)", frequency=105)
Language.objects.create(name="Nepali", frequency=100)
Language.objects.create(name="Luxembourgish", frequency=97)
Language.objects.create(name="Southern Azerbaijani", frequency=95)
Language.objects.create(name="Alemannic", frequency=94)
Language.objects.create(name="Occitan", frequency=92)
Language.objects.create(name="Tatar", frequency=88)
Language.objects.create(name="Gujarati", frequency=84)
Language.objects.create(name="Classical Chinese", frequency=83)
Language.objects.create(name="Bashkir", frequency=82)
Language.objects.create(name="Waray", frequency=81)
Language.objects.create(name="Assamese", frequency=78)
Language.objects.create(name="Sundanese", frequency=76)
Language.objects.create(name="Somali", frequency=76)
Language.objects.create(name="Kirghiz", frequency=74)
Language.objects.create(name="Khmer", frequency=72)
Language.objects.create(name="West Frisian", frequency=71)
Language.objects.create(name="Aragonese", frequency=69)
Language.objects.create(name="Min Nan", frequency=68)
Language.objects.create(name="Tajik", frequency=68)
Language.objects.create(name="Sinhalese", frequency=68)
Language.objects.create(name="Bavarian", frequency=67)
Language.objects.create(name="Minangkabau", frequency=65)
Language.objects.create(name="Kurdish (Kurmanji)", frequency=63)
Language.objects.create(name="Odia", frequency=62)
Language.objects.create(name="Yiddish", frequency=55)
Language.objects.create(name="Low Saxon", frequency=52)
Language.objects.create(name="Wu", frequency=52)
Language.objects.create(name="Amharic", frequency=50)
Language.objects.create(name="Interlingua", frequency=48)
Language.objects.create(name="Anglo-Saxon", frequency=48)
Language.objects.create(name="Lombard", frequency=47)
afghan = Language.objects.create(name="Pashto", frequency=47)
Language.objects.create(name="Malagasy", frequency=45)
Language.objects.create(name="Bhojpuri", frequency=44)
Language.objects.create(name="Venetian", frequency=43)
Language.objects.create(name="Ido", frequency=42)
Language.objects.create(name="Sindhi", frequency=42)
Language.objects.create(name="Maltese", frequency=42)
Language.objects.create(name="Western Punjabi", frequency=41)
Language.objects.create(name="Faroese", frequency=41)
Language.objects.create(name="Chechen", frequency=40)
Language.objects.create(name="Limburgish", frequency=40)
Language.objects.create(name="Chuvash", frequency=38)
Language.objects.create(name="Central Bicolano", frequency=38)
Language.objects.create(name="Turkmen", frequency=38)
yoruba = Language.objects.create(name="Yoruba", frequency=37)
Language.objects.create(name="Maithili", frequency=37)
Language.objects.create(name="Sicilian", frequency=36)
Language.objects.create(name="Haitian", frequency=34)
Language.objects.create(name="Mazandarani", frequency=34)
Language.objects.create(name="Sakha", frequency=34)
quechua = Language.objects.create(name="Quechua", frequency=33)
Language.objects.create(name="West Flemish", frequency=33)
Language.objects.create(name="Mingrelian", frequency=32)
Language.objects.create(name="Fiji Hindi", frequency=32)
Language.objects.create(name="Zulu", frequency=32)
Language.objects.create(name="Bishnupriya Manipuri", frequency=31)
gaelic = Language.objects.create(name="Scottish Gaelic", frequency=31)
Language.objects.create(name="Tibetan", frequency=31)
Language.objects.create(name="Piedmontese", frequency=30)
Language.objects.create(name="Zazaki", frequency=30)
Language.objects.create(name="Dutch Low Saxon", frequency=30)
Language.objects.create(name="Volapük", frequency=29)
Language.objects.create(name="Newar", frequency=29)
Language.objects.create(name="Upper Sorbian", frequency=29)
Language.objects.create(name="Hakka", frequency=29)
Language.objects.create(name="Santali", frequency=29)
Language.objects.create(name="Samogitian", frequency=28)
Language.objects.create(name="Banyumasan", frequency=27)
Language.objects.create(name="Northern Sami", frequency=27)
Language.objects.create(name="Sardinian", frequency=27)
Language.objects.create(name="Lao", frequency=27)
Language.objects.create(name="Igbo", frequency=27)
Language.objects.create(name="Acehnese", frequency=26)
Language.objects.create(name="Northern Luri", frequency=26)
Language.objects.create(name="Old Church Slavonic", frequency=26)
Language.objects.create(name="North Frisian", frequency=25)
Language.objects.create(name="Rusyn", frequency=25)
Language.objects.create(name="Crimean Tatar", frequency=25)
Language.objects.create(name="Ligurian", frequency=25)
Language.objects.create(name="Hausa", frequency=25)
Language.objects.create(name="Tulu", frequency=25)
Language.objects.create(name="Cherokee", frequency=25)
Language.objects.create(name="Xhosa", frequency=25)
Language.objects.create(name="Ilocano", frequency=24)
Language.objects.create(name="Meadow Mari", frequency=24)
Language.objects.create(name="Vepsian", frequency=24)
Language.objects.create(name="Picard", frequency=24)
Language.objects.create(name="Interlingue", frequency=24)
Language.objects.create(name="Ladino", frequency=24)
Language.objects.create(name="Emilian-Romagnol", frequency=23)
Language.objects.create(name="Ossetian", frequency=23)
Language.objects.create(name="Extremaduran", frequency=23)
Language.objects.create(name="Buginese", frequency=22)
Language.objects.create(name="Silesian", frequency=22)
Language.objects.create(name="Maori", frequency=22)
Language.objects.create(name="Corsican", frequency=22)
Language.objects.create(name="Kashubian", frequency=22)
Language.objects.create(name="Friulian", frequency=22)
Language.objects.create(name="Manx", frequency=21)
Language.objects.create(name="Chavacano", frequency=21)
Language.objects.create(name="Doteli", frequency=21)
Language.objects.create(name="Buryat", frequency=21)
Language.objects.create(name="Neapolitan", frequency=20)
Language.objects.create(name="Erzya", frequency=20)
Language.objects.create(name="Lezgian", frequency=20)
Language.objects.create(name="Guarani", frequency=20)
Language.objects.create(name="Romansh", frequency=20)
Language.objects.create(name="Papiamentu", frequency=20)
Language.objects.create(name="Pennsylvania German", frequency=20)
Language.objects.create(name="Min Dong", frequency=19)
Language.objects.create(name="Kapampangan", frequency=19)
nahuatl = Language.objects.create(name="Nahuatl", frequency=19)
Language.objects.create(name="Gan", frequency=19)
Language.objects.create(name="Cornish", frequency=19)
Language.objects.create(name="Mirandese", frequency=19)
Language.objects.create(name="Lingua Franca Nova", frequency=19)
Language.objects.create(name="Lower Sorbian", frequency=19)
Language.objects.create(name="Divehi", frequency=19)
Language.objects.create(name="Gorontalo", frequency=19)
Language.objects.create(name="Zhuang", frequency=19)
Language.objects.create(name="Gothic", frequency=19)
Language.objects.create(name="Dzongkha", frequency=19)
Language.objects.create(name="Walloon", frequency=18)
Language.objects.create(name="Komi", frequency=18)
Language.objects.create(name="Uyghur", frequency=18)
Language.objects.create(name="Abkhazian", frequency=18)
Language.objects.create(name="Wolof", frequency=18)
Language.objects.create(name="Atikamekw", frequency=18)
Language.objects.create(name="Norman", frequency=17)
Language.objects.create(name="Livvi-Karelian", frequency=17)
Language.objects.create(name="Palatinate German", frequency=17)
Language.objects.create(name="Avar", frequency=17)
Language.objects.create(name="Tuvan", frequency=17)
Language.objects.create(name="Aromanian", frequency=17)
Language.objects.create(name="Chichewa", frequency=17)
Language.objects.create(name="Hill Mari", frequency=16)
Language.objects.create(name="Zeelandic", frequency=16)
Language.objects.create(name="Udmurt", frequency=16)
Language.objects.create(name="Shona", frequency=16)
Language.objects.create(name="Saterland Frisian", frequency=16)
Language.objects.create(name="Lingala", frequency=16)
Language.objects.create(name="Kabyle", frequency=16)
Language.objects.create(name="Ripuarian", frequency=16)
Language.objects.create(name="Gagauz", frequency=16)
Language.objects.create(name="Banjar", frequency=16)
Language.objects.create(name="Bislama", frequency=16)
oromo = Language.objects.create(name="Oromo", frequency=16)
Language.objects.create(name="Norfolk", frequency=16)
Language.objects.create(name="Twi", frequency=16)
Language.objects.create(name="Akan", frequency=16)
Language.objects.create(name="Dinka", frequency=16)
Language.objects.create(name="Gilaki", frequency=15)
Language.objects.create(name="Hawaiian", frequency=15)
Language.objects.create(name="Franco-Provençal", frequency=15)
Language.objects.create(name="Romani", frequency=15)
Language.objects.create(name="Chamorro", frequency=15)
Language.objects.create(name="Aymara", frequency=14)
Language.objects.create(name="Komi-Permyak", frequency=14)
Language.objects.create(name="Greenlandic", frequency=14)
aramaic = Language.objects.create(name="Aramaic", frequency=14)
Language.objects.create(name="Tetum", frequency=14)
Language.objects.create(name="Latgalian", frequency=14)
Language.objects.create(name="Bambara", frequency=14)
Language.objects.create(name="Adyghe", frequency=14)
Language.objects.create(name="Tarantino", frequency=13)
Language.objects.create(name="Võro", frequency=13)
Language.objects.create(name="Kalmyk", frequency=13)
Language.objects.create(name="Ingush", frequency=13)
Language.objects.create(name="Pontic", frequency=13)
Language.objects.create(name="Kinyarwanda", frequency=12)
Language.objects.create(name="Tok Pisin", frequency=12)
Language.objects.create(name="Lojban", frequency=12)
Language.objects.create(name="Luganda", frequency=12)
Language.objects.create(name="Kirundi", frequency=12)
Language.objects.create(name="Pangasinan", frequency=11)
Language.objects.create(name="Kabiye", frequency=11)
Language.objects.create(name="Nauruan", frequency=11)
Language.objects.create(name="Tahitian", frequency=11)
Language.objects.create(name="Moksha", frequency=11)
Language.objects.create(name="Cheyenne", frequency=11)
Language.objects.create(name="Tsonga", frequency=11)
Language.objects.create(name="Sesotho", frequency=11)
Language.objects.create(name="Fijian", frequency=11)
Language.objects.create(name="Inuktitut", frequency=11)
Language.objects.create(name="Cree", frequency=11)
Language.objects.create(name="Samoan", frequency=10)
Language.objects.create(name="Tswana", frequency=10)
Language.objects.create(name="Swati", frequency=10)
navaho = Language.objects.create(name="Navajo", frequency=9)
Language.objects.create(name="Karachay-Balkar", frequency=9)
Language.objects.create(name="Karakalpak", frequency=9)
Language.objects.create(name="Novial", frequency=9)
Language.objects.create(name="Jamaican Patois", frequency=9)
Language.objects.create(name="Kabardian", frequency=9)
Language.objects.create(name="Kikuyu", frequency=9)
Language.objects.create(name="Sranan", frequency=9)
Language.objects.create(name="Kashmiri", frequency=9)
Language.objects.create(name="Tongan", frequency=8)
Language.objects.create(name="Inupiak", frequency=8)
Language.objects.create(name="Northern Sotho", frequency=7)
Language.objects.create(name="Lak", frequency=7)
Language.objects.create(name="Kongo", frequency=7)
Language.objects.create(name="Tumbuka", frequency=7)
Language.objects.create(name="Sango", frequency=7)
Language.objects.create(name="Fula", frequency=7)
Language.objects.create(name="Pali", frequency=6)
Language.objects.create(name="Ewe", frequency=6)
Language.objects.create(name="Venda", frequency=6)
Language.objects.create(name="Tigrinya", frequency=6)
Language.objects.create(name="Herero", frequency=1)
Language.objects.create(name="Ndonga", frequency=0)
Language.objects.create(name="Choctaw", frequency=0)
Language.objects.create(name="Marshallese", frequency=0)
Language.objects.create(name="Kuanyama", frequency=0)
Language.objects.create(name="Nuosu", frequency=0)
Language.objects.create(name="Hiri Motu", frequency=0)
Language.objects.create(name="Afar", frequency=0)
Language.objects.create(name="Muscogee", frequency=0)
Language.objects.create(name="Kanuri", frequency=0)
algonquin = Language.objects.create(name="Algonquin", frequency=0)
mayan = Language.objects.create(name="Mayan", frequency=0)
iroquois = Language.objects.create(name="Iroquois", frequency=0)
sioux = Language.objects.create(name="Sioux", frequency=0)
anguthimri = Language.objects.create(name="Anguthimri", frequency=0)


bone = Material.objects.create(name="Bone")
cloth = Material.objects.create(name="Cloth")
iron = Material.objects.create(name="Iron")
leather = Material.objects.create(name="Leather")
paper = Material.objects.create(name="Paper")
parchment = Material.objects.create(name="Parchment")
steel = Material.objects.create(name="Steel")
vellum = Material.objects.create(name="Vellum")
wood = Material.objects.create(name="Wood")

book = Medium.objects.create(name="Book")
ebook = Medium.objects.create(
    name="eBook", length_modifier_type="/", length_modifier=20
)
flash_drive = Medium.objects.create(
    name="Flash Drive", length_modifier_type="/", length_modifier=10
)
scrolls = Medium.objects.create(
    name="Scrolls", length_modifier_type="/", length_modifier=20
)
software = Medium.objects.create(
    name="Software", length_modifier_type="/", length_modifier=1
)
tablets = Medium.objects.create(
    name="Tablets", length_modifier_type="/", length_modifier=40
)
