from wod.models.characters.human import Specialty
from wod.models.characters.werewolf import Tribe, Gift, Rite, Camp, Totem

Tribe.objects.create(name="Black Furies", willpower=3)
Tribe.objects.create(name="Bone Gnawers", willpower=4)
Tribe.objects.create(name="Children of Gaia", willpower=4)
Tribe.objects.create(name="Fianna", willpower=3)
Tribe.objects.create(name="Get of Fenris", willpower=3)
Tribe.objects.create(name="Glass Walkers", willpower=3)
Tribe.objects.create(name="Red Talons", willpower=3)
Tribe.objects.create(name="Shadow Lords", willpower=3)
Tribe.objects.create(name="Silent Striders", willpower=3)
Tribe.objects.create(name="Silver Fangs", willpower=3)
Tribe.objects.create(name="Stargazers", willpower=4)
Tribe.objects.create(name="Uktena", willpower=3)
Tribe.objects.create(name="Wendigo", willpower=4)

Specialty.objects.get_or_create(name="Steely Grip", stat="strength")
Specialty.objects.get_or_create(name="Lower Body", stat="strength")
Specialty.objects.get_or_create(name="Strength Reserves", stat="strength")
Specialty.objects.get_or_create(name="Lightning Reflexes", stat="dexterity")
Specialty.objects.get_or_create(name="Preternatural Grace", stat="dexterity")
Specialty.objects.get_or_create(name="Nimble Fingers", stat="dexterity")
Specialty.objects.get_or_create(name="Unbreakable", stat="stamina")
Specialty.objects.get_or_create(name="Tireless", stat="stamina")
Specialty.objects.get_or_create(name="Resilient", stat="stamina")
Specialty.objects.get_or_create(name="Air of Confidence", stat="charisma")
Specialty.objects.get_or_create(name="Captivating Voice", stat="charisma")
Specialty.objects.get_or_create(name="Infectious Humor", stat="charisma")
Specialty.objects.get_or_create(name="Forked Tongue", stat="manipulation")
Specialty.objects.get_or_create(name="Unswerving Logic", stat="manipulation")
Specialty.objects.get_or_create(name="Doubletalk", stat="manipulation")
Specialty.objects.get_or_create(name="Seduction", stat="manipulation")
Specialty.objects.get_or_create(name="Genial", stat="appearance")
Specialty.objects.get_or_create(name="Exotic", stat="appearance")
Specialty.objects.get_or_create(name="Alluring", stat="appearance")
Specialty.objects.get_or_create(name="Noble Bearing", stat="appearance")
Specialty.objects.get_or_create(name="Eyes in the Back of Your Head", stat="perception")
Specialty.objects.get_or_create(name="Farsighted", stat="perception")
Specialty.objects.get_or_create(name="Uncanny Instincts", stat="perception")
Specialty.objects.get_or_create(name="Detail-Oriented", stat="perception")
Specialty.objects.get_or_create(name="Lateral Problem Solver", stat="intelligence")
Specialty.objects.get_or_create(name="Creative Logic", stat="intelligence")
Specialty.objects.get_or_create(name="Probability Calculation", stat="intelligence")
Specialty.objects.get_or_create(name="Trivia", stat="intelligence")
Specialty.objects.get_or_create(name="Snappy Retorts", stat="wits")
Specialty.objects.get_or_create(name="Ambushes", stat="wits")
Specialty.objects.get_or_create(name="Cool-Headed", stat="wits")
Specialty.objects.get_or_create(name="Cunning", stat="wits")
Specialty.objects.get_or_create(name="Ambushes", stat="alertness")
Specialty.objects.get_or_create(name="Eavesdropping", stat="alertness")
Specialty.objects.get_or_create(name="Paranoia", stat="alertness")
Specialty.objects.get_or_create(name="Traps", stat="alertness")
Specialty.objects.get_or_create(name="Scents", stat="alertness")
Specialty.objects.get_or_create(name="Specific sports", stat="athletics")
Specialty.objects.get_or_create(name="Team Play", stat="athletics")
Specialty.objects.get_or_create(name="Swimming", stat="athletics")
Specialty.objects.get_or_create(name="Rock Climbing", stat="athletics")
Specialty.objects.get_or_create(name="Tumbling", stat="athletics")
Specialty.objects.get_or_create(name="Distance Trials", stat="athletics")
Specialty.objects.get_or_create(name="Pentathlon", stat="athletics")
Specialty.objects.get_or_create(name="Boxing", stat="brawl")
Specialty.objects.get_or_create(name="Wrestling", stat="brawl")
Specialty.objects.get_or_create(name="Dirty Infighting", stat="brawl")
Specialty.objects.get_or_create(name="Weaponless Martial Arts", stat="brawl")
Specialty.objects.get_or_create(name="Kailindo", stat="brawl")
Specialty.objects.get_or_create(name="Sense Lies", stat="empathy")
Specialty.objects.get_or_create(name="Hidden Motives", stat="empathy")
Specialty.objects.get_or_create(name="Emotional States", stat="empathy")
Specialty.objects.get_or_create(name="Personality Quirks", stat="empathy")
Specialty.objects.get_or_create(name="Affairs of the Heart", stat="empathy")
Specialty.objects.get_or_create(name="Rhetoric", stat="expression")
Specialty.objects.get_or_create(name="Inspiriting Speeches", stat="expression")
Specialty.objects.get_or_create(name="Poetry", stat="expression")
Specialty.objects.get_or_create(name="Drama", stat="expression")
Specialty.objects.get_or_create(name="Political Doubletalk", stat="expression")
Specialty.objects.get_or_create(name="Social Media", stat="expression")
Specialty.objects.get_or_create(name="Veiled Threats", stat="intimidation")
Specialty.objects.get_or_create(name="Good Cop/Bad Cop", stat="intimidation")
Specialty.objects.get_or_create(name="Blackmail", stat="intimidation")
Specialty.objects.get_or_create(name="Phyiscal Threats", stat="intimidation")
Specialty.objects.get_or_create(name="Revenge", stat="intimidation")
Specialty.objects.get_or_create(name="Compelling", stat="leadership")
Specialty.objects.get_or_create(name="Open", stat="leadership")
Specialty.objects.get_or_create(name="Military", stat="leadership")
Specialty.objects.get_or_create(name="Motivation", stat="leadership")
Specialty.objects.get_or_create(name="Combat Readiness", stat="leadership")
Specialty.objects.get_or_create(name="Shifting Forms", stat="primal_urge")
Specialty.objects.get_or_create(name="Hunting", stat="primal_urge")
Specialty.objects.get_or_create(name="Hunches", stat="primal_urge")
Specialty.objects.get_or_create(name="Reacting", stat="primal_urge")
Specialty.objects.get_or_create(name="Fencing", stat="streetwise")
Specialty.objects.get_or_create(name="Illegal Drugs", stat="streetwise")
Specialty.objects.get_or_create(name="Illegal Guns", stat="streetwise")
Specialty.objects.get_or_create(name="Gangs", stat="streetwise")
Specialty.objects.get_or_create(name="Unsecured Wifi", stat="streetwise")
Specialty.objects.get_or_create(name="White Lies", stat="subterfuge")
Specialty.objects.get_or_create(name="Seduction", stat="subterfuge")
Specialty.objects.get_or_create(name="The Long Con", stat="subterfuge")
Specialty.objects.get_or_create(name="Feigned Innocence", stat="subterfuge")
Specialty.objects.get_or_create(name="Falconry", stat="animal_ken")
Specialty.objects.get_or_create(name="Farm Animals", stat="animal_ken")
Specialty.objects.get_or_create(name="Feral Animals", stat="animal_ken")
Specialty.objects.get_or_create(name="Attack Training", stat="animal_ken")
Specialty.objects.get_or_create(name="Horses", stat="animal_ken")
Specialty.objects.get_or_create(name="Big Cats", stat="animal_ken")
Specialty.objects.get_or_create(name="Dogs", stat="animal_ken")
Specialty.objects.get_or_create(name="Woodwork", stat="crafts")
Specialty.objects.get_or_create(name="Drawing/Painting", stat="crafts")
Specialty.objects.get_or_create(name="Weaving", stat="crafts")
Specialty.objects.get_or_create(name="Carving", stat="crafts")
Specialty.objects.get_or_create(name="Sculpture", stat="crafts")
Specialty.objects.get_or_create(name="Metalworking", stat="crafts")
Specialty.objects.get_or_create(name="Auro Repair", stat="crafts")
Specialty.objects.get_or_create(name="Off-road", stat="drive")
Specialty.objects.get_or_create(name="Motorcycles", stat="drive")
Specialty.objects.get_or_create(name="Heavy Traffic", stat="drive")
Specialty.objects.get_or_create(name="High Speed", stat="drive")
Specialty.objects.get_or_create(name="High Society", stat="etiquette")
Specialty.objects.get_or_create(name="Moots", stat="etiquette")
Specialty.objects.get_or_create(name="Tribal", stat="etiquette")
Specialty.objects.get_or_create(name="Big Business", stat="etiquette")
Specialty.objects.get_or_create(name="Rifles", stat="firearms")
Specialty.objects.get_or_create(name="Pistols", stat="firearms")
Specialty.objects.get_or_create(name="Submachine Guns", stat="firearms")
Specialty.objects.get_or_create(name="Gunsmithing", stat="firearms")
Specialty.objects.get_or_create(name="Marksmanship", stat="firearms")
Specialty.objects.get_or_create(name="Trick Shots", stat="firearms")
Specialty.objects.get_or_create(name="Pickpocketing", stat="larceny")
Specialty.objects.get_or_create(name="Misdirection", stat="larceny")
Specialty.objects.get_or_create(name="Lockpicking", stat="larceny")
Specialty.objects.get_or_create(name="Hotwiring", stat="larceny")
Specialty.objects.get_or_create(name="Safecracking", stat="larceny")
Specialty.objects.get_or_create(name="Swords", stat="melee")
Specialty.objects.get_or_create(name="Spears", stat="melee")
Specialty.objects.get_or_create(name="Improvised Weaponry", stat="melee")
Specialty.objects.get_or_create(name="Klaives", stat="melee")
Specialty.objects.get_or_create(name="Dancing", stat="performance")
Specialty.objects.get_or_create(name="Singing", stat="performance")
Specialty.objects.get_or_create(name="Acting", stat="performance")
Specialty.objects.get_or_create(name="Rock and Roll", stat="performance")
Specialty.objects.get_or_create(name="Guitar Solos", stat="performance")
Specialty.objects.get_or_create(name="Opera", stat="performance")
Specialty.objects.get_or_create(name="Howling", stat="performance")
Specialty.objects.get_or_create(name="Shadowing", stat="stealth")
Specialty.objects.get_or_create(name="Urban", stat="stealth")
Specialty.objects.get_or_create(name="Taking Point", stat="stealth")
Specialty.objects.get_or_create(name="Crowds", stat="stealth")
Specialty.objects.get_or_create(name="Hiding Objects", stat="stealth")
Specialty.objects.get_or_create(name="Foraging", stat="survival")
Specialty.objects.get_or_create(name="Tracking", stat="survival")
Specialty.objects.get_or_create(name="Specific Environments", stat="survival")
Specialty.objects.get_or_create(name="Trapping", stat="survival")
Specialty.objects.get_or_create(name="Color Theory", stat="academics")
Specialty.objects.get_or_create(name="Linguistics", stat="academics")
Specialty.objects.get_or_create(name="Poststructuralism", stat="academics")
Specialty.objects.get_or_create(name="Ethics", stat="academics")
Specialty.objects.get_or_create(name="Metaphysics", stat="academics")
Specialty.objects.get_or_create(name="Sumeria", stat="academics")
Specialty.objects.get_or_create(name="Internet Research", stat="computer")
Specialty.objects.get_or_create(name="Video Editing", stat="computer")
Specialty.objects.get_or_create(name="Photo Manipulation", stat="computer")
Specialty.objects.get_or_create(name="Programming", stat="computer")
Specialty.objects.get_or_create(name="Computer Languages", stat="computer")
Specialty.objects.get_or_create(name="Logic Problems", stat="enigmas")
Specialty.objects.get_or_create(name="Lateral Thinking", stat="enigmas")
Specialty.objects.get_or_create(name="Ancient Mysteries", stat="enigmas")
Specialty.objects.get_or_create(name="Things Werewolves Were Not Meant to Know", stat="enigmas")
Specialty.objects.get_or_create(name="Evidence", stat="investigation")
Specialty.objects.get_or_create(name="Ballistics", stat="investigation")
Specialty.objects.get_or_create(name="Forensics", stat="investigation")
Specialty.objects.get_or_create(name="Fingerprints", stat="investigation")
Specialty.objects.get_or_create(name="Searches", stat="investigation")
Specialty.objects.get_or_create(name="Internet Research", stat="investigation")
Specialty.objects.get_or_create(name="Fitting Punishments", stat="law")
Specialty.objects.get_or_create(name="Litany Breaches", stat="law")
Specialty.objects.get_or_create(name="Human Field", stat="law")
Specialty.objects.get_or_create(name="Emergency Medicine", stat="medicine")
Specialty.objects.get_or_create(name="Forensic Pathology", stat="medicine")
Specialty.objects.get_or_create(name="Neurology", stat="medicine")
Specialty.objects.get_or_create(name="Pharmacology", stat="medicine")
Specialty.objects.get_or_create(name="Poison Treatments", stat="medicine")
Specialty.objects.get_or_create(name="Garou Physiology", stat="medicine")
Specialty.objects.get_or_create(name="Tarot", stat="occult")
Specialty.objects.get_or_create(name="Witchcraft", stat="occult")
Specialty.objects.get_or_create(name="Curses", stat="occult")
Specialty.objects.get_or_create(name="Ghosts", stat="occult")
Specialty.objects.get_or_create(name="Psychometry", stat="occult")
Specialty.objects.get_or_create(name="Garou Lore", stat="occult")
Specialty.objects.get_or_create(name="Accord", stat="rituals")
Specialty.objects.get_or_create(name="Caern", stat="rituals")
Specialty.objects.get_or_create(name="Death", stat="rituals")
Specialty.objects.get_or_create(name="Mystic", stat="rituals")
Specialty.objects.get_or_create(name="Punishment", stat="rituals")
Specialty.objects.get_or_create(name="Renown", stat="rituals")
Specialty.objects.get_or_create(name="Seasonal", stat="rituals")
Specialty.objects.get_or_create(name="Minor", stat="rituals")
Specialty.objects.get_or_create(name="Experiments", stat="science")
Specialty.objects.get_or_create(name="Theory", stat="science")
Specialty.objects.get_or_create(name="Chemistry", stat="science")
Specialty.objects.get_or_create(name="Physics", stat="science")
Specialty.objects.get_or_create(name="Biology", stat="science")
Specialty.objects.get_or_create(name="Mathematics", stat="science")
Specialty.objects.get_or_create(name="Astronomy", stat="science")
Specialty.objects.get_or_create(name="Telecoms", stat="technology")
Specialty.objects.get_or_create(name="Computers", stat="technology")
Specialty.objects.get_or_create(name="Security", stat="technology")
Specialty.objects.get_or_create(name="Communications", stat="technology")
Specialty.objects.get_or_create(name="Jury-Rigging", stat="technology")
Specialty.objects.get_or_create(name="Industrial Espionage", stat="technology")

# Totem.objects.create(name="", cost=0)
# Tribe.objects.create(name="", willpower=3)
# Camp.objects.create(name="", tribe=None)
# Gift.objects.create(name="", rank=1, allowed={"garou": []})
# Rite.objects.create(name="", level=0)
