from core.utils import weighted_choice

from .faction import MageFaction

SPHERE_LIST = [
    "correspondence",
    "spirit",
    "time",
    "forces",
    "matter",
    "life",
    "entropy",
    "prime",
    "mind",
]

ABILITY_LIST = [
    "awareness",
    "art",
    "leadership",
    "animal_kinship",
    "blatancy",
    "carousing",
    "do",
    "flying",
    "high_ritual",
    "lucid_dreaming",
    "search",
    "seduction",
    "martial_arts",
    "meditation",
    "research",
    "survival",
    "technology",
    "acrobatics",
    "archery",
    "biotech",
    "energy_weapons",
    "hypertech",
    "jetpack",
    "riding",
    "torture",
    "cosmology",
    "enigmas",
    "esoterica",
    "law",
    "occult",
    "politics",
    "area_knowledge",
    "belief_systems",
    "cryptography",
    "demolitions",
    "finance",
    "lore",
    "media",
    "pharmacopeia",
    "alertness",
    "athletics",
    "brawl",
    "empathy",
    "expression",
    "intimidation",
    "streetwise",
    "subterfuge",
    "crafts",
    "drive",
    "etiquette",
    "firearms",
    "melee",
    "stealth",
    "academics",
    "computer",
    "investigation",
    "medicine",
    "science",
    "cooking",
    "diplomacy",
    "instruction",
    "intrigue",
    "intuition",
    "mimicry",
    "negotiation",
    "newspeak",
    "scan",
    "scrounging",
    "style",
    "blind_fighting",
    "climbing",
    "disguise",
    "elusion",
    "escapology",
    "fast_draw",
    "fast_talk",
    "fencing",
    "fortune_telling",
    "gambling",
    "gunsmith",
    "heavy_weapons",
    "hunting",
    "hypnotism",
    "jury_rigging",
    "microgravity_operations",
    "misdirection",
    "networking",
    "pilot",
    "psychology",
    "security",
    "speed_reading",
    "swimming",
    "conspiracy_theory",
    "chantry_politics",
    "covert_culture",
    "cultural_savvy",
    "helmsman",
    "history_knowledge",
    "power_brokering",
    "propaganda",
    "theology",
    "unconventional_warface",
    "vice",
]

PRIMARY_ABILITIES = [
    "awareness",
    "art",
    "leadership",
    "martial_arts",
    "meditation",
    "research",
    "survival",
    "technology",
    "cosmology",
    "enigmas",
    "esoterica",
    "law",
    "occult",
    "politics",
    "alertness",
    "athletics",
    "brawl",
    "empathy",
    "expression",
    "intimidation",
    "streetwise",
    "subterfuge",
    "crafts",
    "drive",
    "etiquette",
    "firearms",
    "melee",
    "stealth",
    "academics",
    "computer",
    "investigation",
    "medicine",
    "science",
]


def weighted_random_faction():
    faction_probs = {}
    for faction in MageFaction.objects.all():
        if faction.parent is None:
            faction_probs[faction] = 30
        elif faction.parent.parent is None:
            faction_probs[faction] = 10
        elif faction.parent.parent.parent is None:
            faction_probs[faction] = 1
        else:
            faction_probs[faction] = 0
    return weighted_choice(faction_probs, ceiling=100)
